-- Migration ini sudah tidak relevan setelah redesign schema.
-- Role tidak lagi disimpan sebagai enum di tabel users.
-- Sistem role sekarang ada di tabel role_groups, roles, dan kepengurusan.
-- File ini dikosongkan agar urutan migrasi Encore tidak berubah.
