-- Migration ini sudah tidak relelan setelah redesign schema.
-- Status approval sekarang dikelola di tabel persetujuan dengan CHECK constraint.
-- File ini dikosongkan agar urutan migrasi Encore tidak berubah.
