-- Migration ini sudah tidak relelan setelah redesign schema.
-- Status rapat sekarang menggunakan VARCHAR dengan CHECK constraint di migration 2_add_constraints.
-- File ini dikosongkan agar urutan migrasi Encore tidak berubah.
