-- Migration ini sudah tidak relelan setelah redesign schema.
-- Tipe transaksi sekarang menggunakan VARCHAR 'Masuk'/'Keluar' dengan CHECK constraint.
-- File ini dikosongkan agar urutan migrasi Encore tidak berubah.
